# Generated by Django 3.2.16 on 2023-02-28 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tethys_compute.models.dask.dask_field


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CondorPyJob",
            fields=[
                ("condorpyjob_id", models.AutoField(primary_key=True, serialize=False)),
                ("_attributes", models.JSONField(blank=True, default=dict, null=True)),
                ("_num_jobs", models.IntegerField(default=1)),
                (
                    "_remote_input_files",
                    models.JSONField(blank=True, default=list, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CondorPyWorkflow",
            fields=[
                (
                    "condorpyworkflow_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("_max_jobs", models.JSONField(blank=True, default=dict, null=True)),
                ("_config", models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CondorWorkflowNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                (
                    "pre_script",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "pre_script_args",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "post_script",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "post_script_args",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("variables", models.JSONField(blank=True, default=dict, null=True)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=128, null=True)),
                ("retry", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("retry_unless_exit_value", models.IntegerField(blank=True, null=True)),
                ("pre_skip", models.IntegerField(blank=True, null=True)),
                ("abort_dag_on", models.IntegerField(blank=True, null=True)),
                (
                    "abort_dag_on_return_value",
                    models.IntegerField(blank=True, null=True),
                ),
                ("dir", models.CharField(blank=True, max_length=1024, null=True)),
                ("noop", models.BooleanField(default=False)),
                ("done", models.BooleanField(default=False)),
                (
                    "parent_nodes",
                    models.ManyToManyField(
                        related_name="children_nodes",
                        to="tethys_compute.CondorWorkflowNode",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_set",
                        to="tethys_compute.condorpyworkflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("host", models.CharField(max_length=1024)),
            ],
            options={
                "verbose_name": "Scheduler",
                "verbose_name_plural": "Schedulers",
            },
        ),
        migrations.CreateModel(
            name="TethysJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=2048),
                ),
                ("label", models.CharField(max_length=1024)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("execute_time", models.DateTimeField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                ("workspace", models.CharField(default="", max_length=1024)),
                (
                    "extended_properties",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "status_message",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "_process_results_function",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "_status",
                    models.CharField(
                        choices=[
                            ("PEN", "Pending"),
                            ("SUB", "Submitted"),
                            ("RUN", "Running"),
                            ("VAR", "Various"),
                            ("PAS", "Paused"),
                            ("COM", "Complete"),
                            ("ERR", "Error"),
                            ("ABT", "Aborted"),
                            ("VCP", "Various-Complete"),
                            ("RES", "Results-Ready"),
                            ("OTH", "Other"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tethys_jobs",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
            },
        ),
        migrations.CreateModel(
            name="BasicJob",
            fields=[
                (
                    "tethysjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_compute.tethysjob",
                    ),
                ),
            ],
            bases=("tethys_compute.tethysjob",),
        ),
        migrations.CreateModel(
            name="CondorBase",
            fields=[
                (
                    "tethysjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_compute.tethysjob",
                    ),
                ),
                ("cluster_id", models.IntegerField(blank=True, default=0)),
                ("remote_id", models.CharField(blank=True, max_length=32, null=True)),
            ],
            bases=("tethys_compute.tethysjob",),
        ),
        migrations.CreateModel(
            name="CondorScheduler",
            fields=[
                (
                    "scheduler_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_compute.scheduler",
                    ),
                ),
                ("port", models.IntegerField(blank=True, default=22, null=True)),
                ("username", models.CharField(blank=True, max_length=1024, null=True)),
                ("password", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "private_key_path",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "private_key_pass",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
            ],
            options={
                "verbose_name": "HTCondor Scheduler",
                "verbose_name_plural": "HTCondor Schedulers",
            },
            bases=("tethys_compute.scheduler",),
        ),
        migrations.CreateModel(
            name="CondorWorkflowJobNode",
            fields=[
                (
                    "condorpyjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="tethys_compute.condorpyjob",
                    ),
                ),
                (
                    "condorworkflownode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_compute.condorworkflownode",
                    ),
                ),
            ],
            bases=("tethys_compute.condorworkflownode", "tethys_compute.condorpyjob"),
        ),
        migrations.CreateModel(
            name="DaskScheduler",
            fields=[
                (
                    "scheduler_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_compute.scheduler",
                    ),
                ),
                ("timeout", models.IntegerField(blank=True, default=0)),
                ("heartbeat_interval", models.IntegerField(blank=True, default=0)),
                ("dashboard", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Dask Scheduler",
                "verbose_name_plural": "Dask Schedulers",
            },
            bases=("tethys_compute.scheduler",),
        ),
        migrations.CreateModel(
            name="CondorJob",
            fields=[
                (
                    "condorpyjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="tethys_compute.condorpyjob",
                    ),
                ),
                (
                    "condorbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_compute.condorbase",
                    ),
                ),
            ],
            bases=("tethys_compute.condorbase", "tethys_compute.condorpyjob"),
        ),
        migrations.CreateModel(
            name="CondorWorkflow",
            fields=[
                (
                    "condorpyworkflow_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="tethys_compute.condorpyworkflow",
                    ),
                ),
                (
                    "condorbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_compute.condorbase",
                    ),
                ),
            ],
            bases=("tethys_compute.condorbase", "tethys_compute.condorpyworkflow"),
        ),
        migrations.CreateModel(
            name="DaskJob",
            fields=[
                (
                    "tethysjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_compute.tethysjob",
                    ),
                ),
                ("key", models.CharField(max_length=1024, null=True)),
                ("forget", models.BooleanField(default=False)),
                (
                    "result",
                    tethys_compute.models.dask.dask_field.DaskSerializedField(
                        blank=True, null=True
                    ),
                ),
                (
                    "scheduler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tethys_compute.daskscheduler",
                    ),
                ),
            ],
            bases=("tethys_compute.tethysjob",),
        ),
        migrations.AddField(
            model_name="condorbase",
            name="scheduler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tethys_compute.condorscheduler",
            ),
        ),
    ]
