# Generated by Django 2.2.8 on 2020-04-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0001_initial_30'),
    ]

    operations = [
        migrations.AddField(
            model_name='tethysjob',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='tethys_jobs', to='auth.Group',
                                         verbose_name='groups'),
        ),
    ]
