# Generated by Django 5.2.9 on 2026-08-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_compute", "0002_alter_tethysjob_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="condorworkflow",
            name="node_statuses_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="condorworkflownode",
            name="cached_node_status",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="tethysjob",
            name="_last_status_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
