# Generated by Django 2.1.8 on 2019-05-06 17:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0002_daskjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condorpyjob',
            name='_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='condorpyjob',
            name='_remote_input_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='condorpyworkflow',
            name='_max_jobs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='condorworkflownode',
            name='variables',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='tethysjob',
            name='extended_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
