# Generated by Django 3.2.10 on 2021-12-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0004_auto_20211221_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condorpyworkflow',
            name='_max_jobs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='condorworkflownode',
            name='variables',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='tethysjob',
            name='extended_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
