# Generated by Django 3.2.10 on 2021-12-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0005_auto_20211221_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condorpyjob',
            name='_attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
