# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0006_auto_20151221_2207'),
        ('tethys_compute', '0006_auto_20151026_2142'),
    ]

    operations = [
    ]
