# Generated by Django 3.2.10 on 2022-01-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = []

    dependencies = [
        ('tethys_compute', '0006_alter_condorpyjob__attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='condorscheduler',
            name='port',
            field=models.IntegerField(blank=True, default=22, null=True),
        ),
        migrations.AlterModelOptions(
            name='condorscheduler',
            options={'verbose_name': 'HTCondor Scheduler', 'verbose_name_plural': 'HTCondor Schedulers'},
        ),
        migrations.AlterModelOptions(
            name='daskscheduler',
            options={'verbose_name': 'Dask Scheduler', 'verbose_name_plural': 'Dask Schedulers'},
        ),
        migrations.AlterModelOptions(
            name='scheduler',
            options={'verbose_name': 'Scheduler', 'verbose_name_plural': 'Schedulers'},
        ),
    ]
