# Generated by Django 3.2.10 on 2022-01-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0006_alter_condorpyjob__attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='condorscheduler',
            name='port',
            field=models.IntegerField(blank=True, default=22, null=True),
        ),
    ]
