# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tethys_compute.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0007_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondorBase',
            fields=[
                ('tethysjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_compute.TethysJob')),
                ('cluster_id', models.IntegerField(blank=True, default=0)),
                ('remote_id', models.CharField(blank=True, max_length=32, null=True)),
                ('_scheduler', models.ForeignKey(blank=True, db_column=b'scheduler', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tethys_compute.Scheduler')),
            ],
            bases=('tethys_compute.tethysjob',),
        ),
        migrations.CreateModel(
            name='CondorPyJob',
            fields=[
                ('condorpyjob_id', models.AutoField(primary_key=True, serialize=False)),
                ('attributes', tethys_compute.utilities.DictionaryField(default=b'')),
                ('num_jobs', models.IntegerField(default=1)),
                ('remote_input_files', tethys_compute.utilities.ListField(default=b'')),
            ],
        ),
        migrations.AddField(
            model_name='condorjob',
            name='condorbase_ptr',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='tethys_compute.CondorBase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condorjob',
            name='condorpyjob_ptr',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tethys_compute.CondorPyJob'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='condorjob',
            name='condorpy_template_name',
        ),
        migrations.RemoveField(
            model_name='condorjob',
            name='executable',
        ),
    ]
