# Generated by Django 3.2.10 on 2022-01-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0007_condorscheduler_port'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condorscheduler',
            options={'verbose_name': 'HTCondor Scheduler', 'verbose_name_plural': 'HTCondor Schedulers'},
        ),
        migrations.AlterModelOptions(
            name='daskscheduler',
            options={'verbose_name': 'Dask Scheduler', 'verbose_name_plural': 'Dask Schedulers'},
        ),
        migrations.AlterModelOptions(
            name='scheduler',
            options={'verbose_name': 'Scheduler', 'verbose_name_plural': 'Schedulers'},
        ),
    ]
