# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:53
from __future__ import unicode_literals

from django.db import migrations


def migrate_condorjobs(apps, schema_editor):
    """
    Copy data from old CondorJob model to new CondorBase and CondorPyJob models.

    Args:
        apps: Historical version of the models from django.apps.registry.Apps
        schema_editor: Instance of SchemaEditor for manual DB editing.
    """
    CondorJob = apps.get_model('tethys_compute', 'CondorJob')
    CondorBase = apps.get_model('tethys_compute', 'CondorBase')
    CondorPyJob = apps.get_model('tethys_compute', 'CondorPyJob')

    condorjobs = CondorJob.objects.all()

    for condorjob in condorjobs:
        condorbase = CondorBase(tethysjob_ptr=condorjob.tethys_job,
                                cluster_id=condorjob.cluster_id,
                                remote_id=condorjob.remote_id,
                                _scheduler=condorjob.scheduler)
        tethysjob = condorbase.tethysjob_ptr
        condorbase.creation_time = tethysjob.creation_time
        condorbase.user_id = tethysjob.user_id
        condorbase.save()

        condorpyjob = CondorPyJob(attributes=condorjob.attributes,
                                  num_jobs=condorjob.num_jobs,
                                  remote_input_files=condorjob.remote_input_files)
        condorpyjob.save()

        condorjob.condorbase_ptr = condorbase
        condorjob.condorpyjob_ptr = condorpyjob
        condorjob.save()


def unmigrate_condorjobs(apps, schema_editor):
    """
    Copy data from new CondorBase and CondorPyJob models back to old CondorJob model.

    Args:
        apps: Historical version of the models from django.apps.registry.Apps
        schema_editor: Instance of SchemaEditor for manual DB editing.
    """
    CondorJob = apps.get_model('tethys_compute', 'CondorJob')

    condorjobs = CondorJob.objects.all()
    for condorjob in condorjobs:
        condorbase = condorjob.condorbase_ptr
        condorjob.tethys_job = condorbase.tethysjob_ptr
        condorjob.cluster_id =condorbase.cluster_id
        condorjob.remote_id = condorbase.remote_id
        condorjob.scheduler = condorbase._scheduler

        condorpyjob = condorjob.condorpyjob_ptr
        condorjob.attributes = condorpyjob.attributes
        condorjob.num_jobs = condorpyjob.num_jobs
        condorjob.remote_input_files = condorpyjob.remote_input_files

        condorjob.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0008_start_condorjob_refactor'),
    ]

    operations = [
        migrations.RunPython(code=migrate_condorjobs, reverse_code=migrations.RunPython.noop)
    ]
