# Generated by Django 3.2.10 on 2022-01-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0008_auto_20220114_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condorscheduler',
            name='port',
            field=models.CharField(blank=True, default='22', max_length=1024, null=True),
        ),
    ]
