# Generated by Django 3.2.10 on 2022-01-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0009_alter_condorscheduler_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condorscheduler',
            name='port',
            field=models.IntegerField(blank=True, default=22, null=True),
        ),
    ]
