# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0009_condorjob_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condorjob',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='condorjob',
            name='remote_id',
        ),
        migrations.RemoveField(
            model_name='condorjob',
            name='scheduler',
        ),
        migrations.RemoveField(
            model_name='condorjob',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='condorjob',
            name='num_jobs',
        ),
        migrations.RemoveField(
            model_name='condorjob',
            name='remote_input_files',
        ),
        migrations.RemoveField(
            model_name='condorjob',
            name='condorpy_template_name',
        ),
        migrations.RemoveField(
            model_name='condorjob',
            name='executable',
        ),
        migrations.RenameField(
            model_name='condorjob',
            old_name='tethys_job',
            new_name='condorbase_ptr',
        ),
        migrations.AlterField(
            model_name='condorjob',
            name='condorbase_ptr',
            field=models.OneToOneField(auto_created=True, primary_key=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='tethys_compute.CondorBase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condorjob',
            name='condorpyjob_ptr',
            field=models.OneToOneField(auto_created=True, null=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tethys_compute.CondorPyJob'),
            preserve_default=False,
        ),
    ]
