# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_compute', '0011_delete_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='category',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='SettingsCategory',
        ),
    ]
