# environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Mambaforge):
#   $ mamba env create -f micro_environment.yml
# OR
# Create the environment with conda by running the following command (after installing Miniconda or similar):
#   $ conda env create -f micro_environment.yml

name: tethys

channels:
  - conda-forge

dependencies:
  - python>=3.8

  # system dependencies
  - pyopenssl
  - openssl

  # core dependencies
  - django>=4.2,<6
  - channels
  - daphne
  - setuptools_scm
  - pip
  - requests>=2.32.4,<3  # required by lots of things
  - tornado>=6.5,<7
  - cryptography>=44.0.1,<45
  - bcrypt  # also required by channels, docker, daphne, condorpy

  # Gen CLI commands
  - pyyaml
  - jinja2


  # django plugin dependencies
  - django-bootstrap5
  - django-model-utils
  - django-guardian
