export declare type AngleUnits = "deg" | "rad";
export declare const AngleUnits: AngleUnits[];
export declare type Dimension = "width" | "height";
export declare const Dimension: Dimension[];
export declare type Dimensions = "width" | "height" | "both";
export declare const Dimensions: Dimensions[];
export declare type Direction = "clock" | "anticlock";
export declare const Direction: Direction[];
export declare type FontStyle = "normal" | "italic" | "bold" | "bold italic";
export declare const FontStyle: FontStyle[];
export declare type LatLon = "lat" | "lon";
export declare const LatLon: LatLon[];
export declare type LineCap = "butt" | "round" | "square";
export declare const LineCap: LineCap[];
export declare type LineJoin = "miter" | "round" | "bevel";
export declare const LineJoin: LineJoin[];
export declare type Location = "above" | "below" | "left" | "right";
export declare const Location: Location[];
export declare type LegendClickPolicy = "none" | "hide" | "mute";
export declare const LegendClickPolicy: LegendClickPolicy[];
export declare type LegendLocation = "top_left" | "top_center" | "top_right" | "center_left" | "center" | "center_right" | "bottom_left" | "bottom_center" | "bottom_right";
export declare const LegendLocation: LegendLocation[];
export declare type Anchor = LegendLocation;
export declare const Anchor: Anchor[];
export declare type Orientation = "vertical" | "horizontal";
export declare const Orientation: Orientation[];
export declare type OutputBackend = "canvas" | "svg" | "webgl";
export declare const OutputBackend: OutputBackend[];
export declare type RenderLevel = "image" | "underlay" | "glyph" | "annotation" | "overlay";
export declare const RenderLevel: RenderLevel[];
export declare type RenderMode = "canvas" | "css";
export declare const RenderMode: RenderMode[];
export declare type Side = "above" | "below" | "left" | "right";
export declare const Side: Side[];
export declare type Place = Side | "center";
export declare const Place: Place[];
export declare type SpatialUnits = "screen" | "data";
export declare const SpatialUnits: SpatialUnits[];
export declare type StartEnd = "start" | "end";
export declare const StartEnd: StartEnd[];
export declare type VerticalAlign = "top" | "middle" | "bottom";
export declare const VerticalAlign: VerticalAlign[];
export declare type TextAlign = "left" | "right" | "center";
export declare const TextAlign: TextAlign[];
export declare type TextBaseline = "top" | "middle" | "bottom" | "alphabetic" | "hanging" | "ideographic";
export declare const TextBaseline: TextBaseline[];
export declare type TickLabelOrientation = "vertical" | "horizontal" | "parallel" | "normal";
export declare const TickLabelOrientation: TickLabelOrientation[];
export declare type TooltipAttachment = "horizontal" | "vertical" | "left" | "right" | "above" | "below";
export declare const TooltipAttachment: TooltipAttachment[];
export declare type Distribution = "uniform" | "normal";
export declare const Distribution: Distribution[];
export declare type StepMode = "after" | "before" | "center";
export declare const StepMode: StepMode[];
export declare type SizingMode = "stretch_both" | "scale_width" | "scale_height" | "scale_both" | "fixed";
export declare const SizingMode: SizingMode[];
export declare type PaddingUnits = "percent" | "absolute";
export declare const PaddingUnits: PaddingUnits[];
export declare type SliderCallbackPolicy = "continuous" | "throttle" | "mouseup";
export declare const SliderCallbackPolicy: SliderCallbackPolicy[];
export declare type RoundingFunction = "round" | "nearest" | "floor" | "rounddown" | "ceil" | "roundup";
export declare const RoundingFunction: RoundingFunction[];
export declare type UpdateMode = "replace" | "append";
export declare const UpdateMode: UpdateMode[];
export declare type HTTPMethod = "POST" | "GET";
export declare const HTTPMethod: HTTPMethod[];
export declare type Logo = "normal" | "grey";
export declare const Logo: Logo[];
