# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tethys_compute.utilities


class Migration(migrations.Migration):

    replaces = [(b'tethys_apps', '0001_initial'), (b'tethys_apps', '0002_tethysapp_tags'), (b'tethys_apps', '0003_auto_20170505_0350')]

    initial = True

    # dependencies = [
    #     ('tethys_services', '0009_persistentstoreservice'),
    # ]

    operations = [
        migrations.CreateModel(
            name='TethysApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(default=b'', max_length=200, unique=True)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('description', models.TextField(blank=True, default=b'', max_length=1000)),
                ('enable_feedback', models.BooleanField(default=False)),
                ('feedback_emails', tethys_compute.utilities.ListField(blank=True, default=b'')),
                ('index', models.CharField(default=b'', max_length=200)),
                ('icon', models.CharField(default=b'', max_length=200)),
                ('root_url', models.CharField(default=b'', max_length=200)),
                ('color', models.CharField(default=b'', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('show_in_apps_library', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, default=b'', max_length=200)),
            ],
            options={
                'verbose_name': 'Tethys App',
                'verbose_name_plural': 'Installed Apps',
                'permissions': (('view_app', 'Can see app in library'), ('access_app', 'Can access app')),
            },
        ),
        migrations.CreateModel(
            name='TethysAppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('description', models.TextField(blank=True, default=b'', max_length=1000)),
                ('required', models.BooleanField(default=True)),
                ('initializer', models.CharField(default=b'', max_length=1000)),
                ('initialized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('value', models.CharField(blank=True, max_length=1024)),
                ('type', models.CharField(choices=[(b'STRING', b'String'), (b'INTEGER', b'Integer'), (b'FLOAT', b'Float'), (b'BOOLEAN', b'Boolean')], default=b'STRING', max_length=200)),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
        migrations.CreateModel(
            name='DatasetServiceSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('engine', models.CharField(choices=[(b'tethys_dataset_services.engines.CkanDatasetEngine', b'CKAN'), (b'tethys_dataset_services.engines.HydroShareDatasetEngine', b'HydroShare')], default=b'tethys_dataset_services.engines.CkanDatasetEngine', max_length=200)),
                ('dataset_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.DatasetService')),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
        migrations.CreateModel(
            name='PersistentStoreConnectionSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('persistent_store_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.PersistentStoreService')),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
        migrations.CreateModel(
            name='PersistentStoreDatabaseSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('spatial', models.BooleanField(default=False)),
                ('dynamic', models.BooleanField(default=False)),
                ('persistent_store_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.PersistentStoreService')),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
        migrations.CreateModel(
            name='SpatialDatasetServiceSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('engine', models.CharField(choices=[(b'tethys_dataset_services.engines.GeoServerSpatialDatasetEngine', b'GeoServer')], default=b'tethys_dataset_services.engines.GeoServerSpatialDatasetEngine', max_length=200)),
                ('spatial_dataset_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.SpatialDatasetService')),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
        migrations.CreateModel(
            name='WebProcessingServiceSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('web_processing_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.WebProcessingService')),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
        migrations.AddField(
            model_name='tethysappsetting',
            name='tethys_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_set', to='tethys_apps.TethysApp'),
        ),
    ]
