# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import tethys_compute.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TethysApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(default=b'', max_length=200, unique=True)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('description', models.TextField(blank=True, default=b'', max_length=1000)),
                ('enable_feedback', models.BooleanField(default=False)),
                ('feedback_emails', tethys_compute.utilities.ListField(blank=True, default=b'')),
                ('index', models.CharField(default=b'', max_length=200)),
                ('icon', models.CharField(default=b'', max_length=200)),
                ('root_url', models.CharField(default=b'', max_length=200)),
                ('color', models.CharField(default=b'', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('show_in_apps_library', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tethys App',
                'verbose_name_plural': 'Installed Apps',
                'permissions': (('view_app', 'Can see app in library'), ('access_app', 'Can access app')),
            },
        ),
    ]
