# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tethysapp',
            name='tags',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
