# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-14 06:16
from django.db import migrations, models
import tethys_apps.base.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0001_initial_20'),
    ]

    operations = [
        migrations.CreateModel(
            name='TethysExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(default='', max_length=200, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('root_url', models.CharField(default='', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tethys Extension',
                'verbose_name_plural': 'Installed Extensions',
            },
            bases=(models.Model, tethys_apps.base.mixins.TethysBaseMixin),
        ),
    ]
