# Generated by Django 3.2.20 on 2023-09-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tethys_apps", "0002_auto_20230407_2337"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxyapp",
            name="display_external",
            field=models.BooleanField(default=False),
        ),
    ]
