# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0002_tethysextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsetting',
            name='value',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
