# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-29 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_services', '0008_auto_20151023_1427'),
        ('tethys_apps', '0002_tethysapp_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TethysAppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('description', models.TextField(blank=True, default=b'', max_length=1000)),
                ('required', models.BooleanField(default=True)),
                ('initializer', models.CharField(default=b'', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CustomTethysAppSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('value', models.CharField(default=b'', max_length=1000)),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
        migrations.CreateModel(
            name='DatasetServiceSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('engine', models.CharField(choices=[(b'tethys_dataset_services.engines.CkanDatasetEngine', b'CKAN'), (b'tethys_dataset_services.engines.HydroShareDatasetEngine', b'HydroShare')], default=b'tethys_dataset_services.engines.CkanDatasetEngine', max_length=200)),
                ('dataset_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.DatasetService')),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
        migrations.CreateModel(
            name='SpatialDatasetServiceSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('engine', models.CharField(choices=[(b'tethys_dataset_services.engines.GeoServerSpatialDatasetEngine', b'GeoServer')], default=b'tethys_dataset_services.engines.GeoServerSpatialDatasetEngine', max_length=200)),
                ('spatial_dataset_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.SpatialDatasetService')),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
        migrations.CreateModel(
            name='WebProcessingServiceSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('web_processing_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.WebProcessingService')),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
        migrations.AddField(
            model_name='tethysappsetting',
            name='tethys_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_set', to='tethys_apps.TethysApp'),
        ),
    ]
