# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0003_auto_20170316_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetservicesetting',
            name='dataset_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.DatasetService'),
        ),
        migrations.AlterField(
            model_name='spatialdatasetservicesetting',
            name='spatial_dataset_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.SpatialDatasetService'),
        ),
        migrations.AlterField(
            model_name='webprocessingservicesetting',
            name='web_processing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.WebProcessingService'),
        ),
    ]
