# Generated by Django 3.2.10 on 2021-12-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0003_auto_20201209_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tethysapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tethysappsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tethysextension',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
