# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-20 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0001_initial_20'),
    ]

    operations = [
        migrations.CreateModel(
            name='TethysExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(default=b'', max_length=200, unique=True)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('description', models.TextField(blank=True, default=b'', max_length=1000)),
                ('root_url', models.CharField(default=b'', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
