# Generated by Django 2.1.8 on 2019-05-06 17:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0003_python3_compatibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tethysapp',
            name='feedback_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=list, size=None),
        ),
    ]
