# Generated by Django 2.1.8 on 2019-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0003_python3_compatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsetting',
            name='default',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
