# Generated by Django 3.2.20 on 2023-09-28 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tethys_apps", "0003_proxyapp_display_external"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proxyapp",
            old_name="display_external",
            new_name="display_external_icon",
        ),
    ]
