# Generated by Django 3.2.23 on 2024-01-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tethys_apps", "0004_rename_display_external_proxyapp_display_external_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="customsettingbase",
            name="include_in_api",
            field=models.BooleanField(default=False),
        ),
    ]
