# Generated by Django 3.2.16 on 2023-02-08 02:34

from django.db import migrations

def forward(apps, schema_editor):
    breakpoint()
    """ From non inehirtance to post inheritance """
    CustomSetting = apps.get_model('tethys_apps', 'customsetting')
    CustomSimpleSetting = apps.get_model('tethys_apps', 'customsimplesetting')
    db_alias = schema_editor.connection.alias

    for cs in CustomSetting.objects.using(db_alias).all():
        cs_simple = CustomSimpleSetting.objects.create(tethys_app = cs.tethys_app, customsetting_ptr=cs, value=cs.value_temp, default=cs.default_temp, type=cs.type_temp)
        cs_simple.save()

def backward(apps, schema_editor):
    breakpoint()
    """ From non inehirtance to post inheritance """
    CustomSetting = apps.get_model('tethys_apps', 'customsetting')
    CustomSimpleSetting = apps.get_model('tethys_apps', 'customsimplesetting')
    db_alias = schema_editor.connection.alias

    for cs in CustomSetting.objects.using(db_alias).all():
        selected_cs = CustomSimpleSetting.objects.using(db_alias).get(customsetting_ptr=cs)
        cs.value_temp = selected_cs.value
        cs.default_temp = selected_cs.default
        cs.type_temp = selected_cs.type
        cs.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0004_auto_20230206_2145'),
    ]

    operations = [
         migrations.RunPython(forward, backward)
    ]
