# Generated by Django 3.2.12 on 2022-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0005_schedulersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyapp',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tethysapp',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
