# Generated by Django 3.2.16 on 2023-02-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0005_auto_20230223_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name="oldcustomsetting",
        ),
    ]
