# Generated by Django 3.2.16 on 2023-02-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0005_auto_20230208_0234'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='customsettingbase',
            name='default_temp',
        ),
        migrations.RemoveField(
            model_name='customsettingbase',
            name='type_temp',
        ),
        migrations.RemoveField(
            model_name='customsettingbase',
            name='value_temp',
        )

    ]
