# Generated by Django 2.1.8 on 2019-08-22 04:56

from django.db import migrations, models
import tethys_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0005_customsetting_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('endpoint', models.CharField(max_length=1024, validators=[tethys_services.models.validate_url])),
                ('logo_url', models.CharField(blank=True, max_length=100, validators=[tethys_services.models.validate_url])),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('show_in_apps_library', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proxy App',
                'verbose_name_plural': 'Proxy Apps',
            },
        ),
    ]
