# Generated by Django 2.1.8 on 2019-07-22 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_services', '0002_threddsservice'),
        ('tethys_apps', '0005_customsetting_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreddsServiceSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.TethysAppSetting')),
                ('thredds_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.ThreddsService')),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
    ]
