# Generated by Django 5.2.9 on 2026-03-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_apps", "0007_tethysapp_back_url"),
        ("tethys_services", "0002_auto_20260305_1724"),
    ]

    operations = [
        # Add new fields
        migrations.RenameField(
            model_name="persistentstoreconnectionsetting",
            old_name="persistent_store_service",
            new_name="persistent_store_service_postgres",
        ),
        migrations.RenameField(
            model_name="persistentstoredatabasesetting",
            old_name="persistent_store_service",
            new_name="persistent_store_service_postgres",
        ),
        migrations.AddField(
            model_name="persistentstoreconnectionsetting",
            name="persistent_store_service_sqlite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                to="tethys_services.SQLitePersistentStoreService",
            ),
        ),
        migrations.AddField(
            model_name="persistentstoredatabasesetting",
            name="persistent_store_service_sqlite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                to="tethys_services.SQLitePersistentStoreService",
            ),
        ),
    ]
