# Generated by Django 5.2.9 on 2026-03-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_apps", "0007_tethysapp_back_url"),
        ("tethys_services", "0002_auto_20260305_1724"),
    ]

    operations = [
        # Remove old ForeignKey field
        migrations.RemoveField(
            model_name="persistentstoreconnectionsetting",
            name="persistent_store_service",
        ),
        migrations.RemoveField(
            model_name="persistentstoredatabasesetting",
            name="persistent_store_service",
        ),
        # Add new fields for GenericForeignKey
        migrations.AddField(
            model_name="persistentstoreconnectionsetting",
            name="content_type",
            field=models.ForeignKey(to="contenttypes.ContentType", on_delete=models.CASCADE, null=True),
        ),
        migrations.AddField(
            model_name="persistentstoreconnectionsetting",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="persistentstoredatabasesetting",
            name="content_type",
            field=models.ForeignKey(to="contenttypes.ContentType", on_delete=models.CASCADE, null=True),
        ),
        migrations.AddField(
            model_name="persistentstoredatabasesetting",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
