# Generated by Django 5.2.9 on 2026-03-06 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tethys_apps", "0007_tethysapp_back_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persistentstoreconnectionsetting",
            name="persistent_store_service",
        ),
        migrations.RemoveField(
            model_name="persistentstoredatabasesetting",
            name="persistent_store_service",
        ),
        migrations.AddField(
            model_name="persistentstoreconnectionsetting",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="persistentstoreconnectionsetting",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="persistentstoredatabasesetting",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="persistentstoredatabasesetting",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
