# Generated by Django 5.2.9 on 2026-03-13 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_apps', '0007_tethysapp_back_url'),
        ('tethys_services', '0002_secureimageryservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureImageryServiceSetting',
            fields=[
                ('tethysappsetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_apps.tethysappsetting')),
                ('secure_imagery_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tethys_services.secureimageryservice')),
            ],
            bases=('tethys_apps.tethysappsetting',),
        ),
    ]
