# Generated by Django 5.2.14 on 2026-05-28 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tethys_apps",
            "0008_remove_persistentstoreconnectionsetting_persistent_store_service_and_more",
        ),
        ("tethys_services", "0003_securemapservice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureMapServiceSetting",
            fields=[
                (
                    "tethysappsetting_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_apps.tethysappsetting",
                    ),
                ),
                (
                    "secure_map_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tethys_services.securemapservice",
                    ),
                ),
            ],
            bases=("tethys_apps.tethysappsetting",),
        ),
    ]
