# Generated by Django 5.2.17 on 2026-09-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_apps", "0009_securemapservicesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="tethysapp",
            name="required_oauth2_providers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
