# Generated by Django 5.2.17 on 2026-08-25 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_apps", "0009_securemapservicesetting"),
        ("tethys_services", "0006_basemapservice_basemapimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasemapServiceSetting",
            fields=[
                (
                    "tethysappsetting_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_apps.tethysappsetting",
                    ),
                ),
                (
                    "basemap_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tethys_services.basemapservice",
                    ),
                ),
            ],
            bases=("tethys_apps.tethysappsetting",),
        ),
    ]
