# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '3.4.1.dev24+gb092a0af.d20220421'
version_tuple = (3, 4, 1, 'dev24', 'gb092a0af.d20220421')
