# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '3.4.1.dev22+g8bff1112.d20220421'
version_tuple = (3, 4, 1, 'dev22', 'g8bff1112.d20220421')
