# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-29 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('default', models.FloatField()),
                ('units', models.CharField(max_length=100)),
                ('applies_to', models.TextField()),
                ('impose_default', models.BooleanField(default=True)),
                ('help', models.TextField()),
                ('_handler', models.TextField()),
            ],
            options={
                'verbose_name': 'Quota',
            },
        ),
    ]
