# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-29 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_quotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcequota',
            name='codename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
