# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_quotas', '0002_auto_20190129_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcequota',
            options={'verbose_name': 'Resource Quota'},
        ),
    ]
