# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_quotas', '0003_auto_20190131_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('entity_type', models.TextField()),
                ('value', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('resource_quota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tethys_quotas.ResourceQuota')),  # noqa: E501
            ],
            options={
                'verbose_name': 'Entity Quota',
            },
        ),
    ]
