# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_quotas', '0004_entityquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcequota',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
