# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-14 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tethys_apps', '0003_python3_compatibility'),
        ('tethys_quotas', '0005_resourcequota_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TethysAppQuota',
            fields=[
                ('entityquota_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_quotas.EntityQuota')),  # noqa E501
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tethys_apps.TethysApp')),
            ],
            bases=('tethys_quotas.entityquota',),
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('entityquota_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_quotas.EntityQuota')),  # noqa E501
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tethys_quotas.entityquota',),
        ),
        migrations.RemoveField(
            model_name='entityquota',
            name='entity_id',
        ),
    ]
