# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-14 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_quotas', '0006_auto_20190214_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityquota',
            old_name='resource_quota_id',
            new_name='resource_quota',
        ),
        migrations.RemoveField(
            model_name='entityquota',
            name='entity_type',
        ),
    ]
