# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-14 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_quotas', '0007_auto_20190214_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tethysappquota',
            options={'verbose_name': 'Tethys App Quota'},
        ),
        migrations.AlterModelOptions(
            name='userquota',
            options={'verbose_name': 'User Quota'},
        ),
    ]
