# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-21 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_quotas', '0008_auto_20190214_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityquota',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
