# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_quotas', '0009_auto_20190221_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityquota',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
