# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_quotas', '0010_auto_20190227_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityquota',
            name='active',
        ),
    ]
