# Generated by Django 5.2.7 on 2025-11-03 22:30
# Applied only if django_tenants is installed

import django.db.models.deletion
from django.db import migrations, models

from tethys_portal.optional_dependencies import has_module

if has_module("django_tenants"):
    import django_tenants.postgresql_backend.base

    class Migration(migrations.Migration):

        initial = True

        dependencies = []
        operations = [
            migrations.CreateModel(
                name="Tenant",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    (
                        "schema_name",
                        models.CharField(
                            db_index=True,
                            max_length=63,
                            unique=True,
                            validators=[
                                django_tenants.postgresql_backend.base._check_schema_name
                            ],
                        ),
                    ),
                    ("name", models.CharField(max_length=100)),
                    ("created_on", models.DateField(auto_now_add=True)),
                ],
                options={
                    "abstract": False,
                },
            ),
            migrations.CreateModel(
                name="Domain",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    (
                        "domain",
                        models.CharField(db_index=True, max_length=253, unique=True),
                    ),
                    ("is_primary", models.BooleanField(db_index=True, default=True)),
                    (
                        "tenant",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="domains",
                            to="tethys_tenants.tenant",
                        ),
                    ),
                ],
                options={
                    "abstract": False,
                },
            ),
        ]
