#!/usr/bin/env python3
"""
Categorized pytest test failures
Generated from: pytest_output.txt
"""

categorized_test_failures = {
    "database_access_issues": [],
    "model_does_not_exist_issues": [
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test__init__.py",
            "class_name": "TethysCommandTests",
            "method_name": "test_test_command",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test__init__.py::TethysCommandTests::test_test_command",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test__init__.py",
            "class_name": "TethysCommandTests",
            "method_name": "test_test_command_help",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test__init__.py::TethysCommandTests::test_test_command_help",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test__init__.py",
            "class_name": "TethysCommandTests",
            "method_name": "test_test_command_options",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test__init__.py::TethysCommandTests::test_test_command_options",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test__init__.py",
            "class_name": "TethysCommandTests",
            "method_name": "test_test_command_options_verbose",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test__init__.py::TethysCommandTests::test_test_command_options_verbose",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_add_geoserver_rest_to_endpoint",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_add_geoserver_rest_to_endpoint",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_gen_salt_string_for_setting_with_empty_secrets",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_gen_salt_string_for_setting_with_empty_secrets",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_gen_salt_string_for_setting_with_no_previous_salt_strings",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_gen_salt_string_for_setting_with_no_previous_salt_strings",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_gen_salt_string_for_setting_with_previous_salt_strings",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_gen_salt_string_for_setting_with_previous_salt_strings",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_gen_salt_string_for_setting_with_secrets_deleted_or_changed",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_gen_salt_string_for_setting_with_secrets_deleted_or_changed",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_generate_salt_string",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_generate_salt_string",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_get_manage_path",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_get_manage_path",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_get_manage_path_error",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_get_manage_path_error",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_legacy_conda_run_command",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_legacy_conda_run_command",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_load_conda_commands_attribute_error",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_load_conda_commands_attribute_error",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_load_conda_commands_fallback_to_local",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_load_conda_commands_fallback_to_local",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_load_conda_commands_first_module_success",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_load_conda_commands_first_module_success",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_load_conda_commands_second_module_success",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_load_conda_commands_second_module_success",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_local_conda_commands_attributes",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_local_conda_commands_attributes",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_new_conda_run_command",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_new_conda_run_command",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_new_conda_run_command_keyboard_interrupt",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_new_conda_run_command_keyboard_interrupt",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_new_conda_run_command_with_error",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_new_conda_run_command_with_error",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_prompt_yes_or_no__accept_default_no",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_prompt_yes_or_no__accept_default_no",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_prompt_yes_or_no__accept_default_yes",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_prompt_yes_or_no__accept_default_yes",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_prompt_yes_or_no__invalid_first",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_prompt_yes_or_no__invalid_first",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_prompt_yes_or_no__system_exit",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_prompt_yes_or_no__system_exit",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_run_process",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_run_process",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_run_process_keyboardinterrupt",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_run_process_keyboardinterrupt",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_setup_django",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_setup_django",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_setup_django_supress_output",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_setup_django_supress_output",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_cli_helper.py",
            "class_name": "TestCliHelper",
            "method_name": "test_shell_run_command_auto_yes_for_install",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_cli_helper.py::TestCliHelper::test_shell_run_command_auto_yes_for_install",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_cli/test_proxyapps_commands.py",
            "class_name": "TestProxyAppsCommand",
            "method_name": "test_add_proxyapp_integrity_error",
            "full_identifier": "tests/unit_tests/test_tethys_cli/test_proxyapps_commands.py::TestProxyAppsCommand::test_add_proxyapp_integrity_error",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_config/test_context_processors.py",
            "class_name": "TestTethysConfigContextProcessors",
            "method_name": "test_tethys_global_settings_context_single_app_mode",
            "full_identifier": "tests/unit_tests/test_tethys_config/test_context_processors.py::TestTethysConfigContextProcessors::test_tethys_global_settings_context_single_app_mode",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
        {
            "file_path": "tests/unit_tests/test_tethys_quotas/test_enforce_quota.py",
            "class_name": "DecoratorsTest",
            "method_name": "test_enforce_quota_applies_to_app",
            "full_identifier": "tests/unit_tests/test_tethys_quotas/test_enforce_quota.py::DecoratorsTest::test_enforce_quota_applies_to_app",
            "error_type": "model_does_not_exist",
            "error_message": "tethys_apps.models.TethysApp.DoesNotExist: TethysApp matching query does not exist",
            "model_name": "TethysApp",
        },
    ],
    "missing_module_issues": [],
    "url_routing_issues": [],
}

# Summary Statistics
summary = {
    "database_access_issues": 0,
    "model_does_not_exist_issues": 33,
    "missing_module_issues": 0,
    "url_routing_issues": 0,
}

# Total issues: 33
