# Generated by Django 5.2.9 on 2026-03-13 15:41

import fernet_fields.fields
import tethys_services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_services", "0001_initial_40"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureImageryService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "endpoint",
                    models.CharField(
                        max_length=1024,
                        validators=[tethys_services.models.validate_url],
                    ),
                ),
                ("api_key", fernet_fields.fields.EncryptedTextField()),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Secure Imagery Service",
                "verbose_name_plural": "Secure Imagery Services",
            },
        ),
    ]
