# Generated by Django 5.2.9 on 2026-03-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_services", "0001_initial_40"),
        ("tethys_apps", "0001_initial_41"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersistentStoreService",
            new_name="PostgresPersistentStoreService",
        ),
        migrations.CreateModel(
            name="SQLitePersistentStoreService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "engine",
                    models.CharField(
                        choices=[("sqlite", "SQLite")],
                        default="sqlite",
                        max_length=50,
                    ),
                ),
                ("dir_path", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "SQLite Persistent Store Service",
                "verbose_name_plural": "SQLite Persistent Store Services",
                "db_table": "tethys_services_persistentstoreservice_sqlite",
            },
        ),
    ]
