# Generated by Django 3.2.12 on 2026-03-04

from django.db import migrations, models

class Migration(migrations.Migration):
    initial = False

    dependencies = [
        ("tethys_services", "0001_initial_40"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE tethys_services_persistentstoreservice RENAME TO tethys_services_persistentstoreservice_postgres;",
            reverse_sql="ALTER TABLE tethys_services_persistentstoreservice_postgres RENAME TO tethys_services_persistentstoreservice;",
        ),
        migrations.CreateModel(
            name="SQLitePersistentStoreService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("engine", models.CharField(
                    choices=[("sqlite", "SQLite")],
                    default="sqlite",
                    max_length=50,
                )),
                ("dir_path", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "SQLite Persistent Store Service",
                "verbose_name_plural": "SQLite Persistent Store Services",
                "db_table": "tethys_services_persistentstoreservice_sqlite",
            }
        ),
    ]
