# Generated by Django 2.1.8 on 2019-07-22 04:20

from django.db import migrations, models
import tethys_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_services', '0001_initial_20'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreddsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('wms_endpoint', models.CharField(max_length=1024, validators=[tethys_services.models.validate_thredds_service_endpoint])),
                ('local_file_path', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'Thredds Service',
                'verbose_name_plural': 'Thredds Services',
            },
        ),
    ]
