# Generated by Django 5.2.9 on 2026-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tethys_apps",
            "0008_remove_persistentstoreconnectionsetting_persistent_store_service_and_more",
        ),
        ("tethys_services", "0001_initial_40"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersistentStoreService",
            new_name="PostgresPersistentStoreService",
        ),
        migrations.AlterModelTable(
            name="postgrespersistentstoreservice",
            table="tethys_services_persistentstoreservice_postgres",
        ),
        migrations.AlterModelOptions(
            name="postgrespersistentstoreservice",
            options={
                "verbose_name": "PostgreSQL Persistent Store Service",
                "verbose_name_plural": "PostgreSQL Persistent Store Services",
            },
        ),
        migrations.AlterField(
            model_name="postgrespersistentstoreservice",
            name="engine",
            field=models.CharField(
                choices=[("postgresql", "PostgreSQL"), ("sqlite", "SQLite")],
                default="postgresql",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SQLitePersistentStoreService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "engine",
                    models.CharField(
                        choices=[("postgresql", "PostgreSQL"), ("sqlite", "SQLite")],
                        default="sqlite",
                        max_length=50,
                    ),
                ),
                ("dir_path", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "SQLite Persistent Store Service",
                "verbose_name_plural": "SQLite Persistent Store Services",
                "db_table": "tethys_services_persistentstoreservice_sqlite",
            },
        ),
    ]
