# Generated by Django 5.2.14 on 2026-05-28 07:46

import encrypted_fields.fields
import tethys_services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_services", "0002_postgrespersistentstoreservice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureMapService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("legend_title", models.CharField(max_length=100, unique=True)),
                (
                    "endpoint",
                    models.CharField(
                        max_length=1024,
                        validators=[tethys_services.models.validate_url],
                    ),
                ),
                (
                    "authentication_method",
                    models.CharField(
                        blank=True,
                        choices=[("api_key", "API Key"), ("oauth", "OAuth")],
                        max_length=100,
                    ),
                ),
                (
                    "api_key",
                    encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
                ),
                ("oauth_provider", models.CharField(blank=True, max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("ImageWMS", "WMS"),
                            ("GML", "GML"),
                            ("geojson", "GeoJSON"),
                        ],
                        default="ImageWMS",
                        max_length=50,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict, null=True)),
                ("use_proxy", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Secure Map Service",
                "verbose_name_plural": "Secure Map Services",
            },
        ),
        migrations.AlterField(
            model_name="postgrespersistentstoreservice",
            name="engine",
            field=models.CharField(
                choices=[("postgresql", "PostgreSQL")],
                default="postgresql",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sqlitepersistentstoreservice",
            name="engine",
            field=models.CharField(
                choices=[("sqlite", "SQLite")], default="sqlite", max_length=50
            ),
        ),
    ]
