# Generated by Django 5.2.17 on 2026-09-23 21:34

import encrypted_fields.fields
import tethys_services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_services", "0002_postgrespersistentstoreservice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureMapService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("legend_title", models.CharField(blank=True, max_length=100)),
                (
                    "endpoint",
                    models.CharField(
                        max_length=1024,
                        validators=[tethys_services.models.validate_url],
                    ),
                ),
                (
                    "authentication_method",
                    models.CharField(
                        blank=True,
                        choices=[("api_key", "API Key"), ("oauth2", "OAuth2")],
                        max_length=100,
                    ),
                ),
                (
                    "api_key",
                    encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
                ),
                ("oauth2_provider", models.CharField(blank=True, max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("ImageWMS", "WMS"),
                            ("GML", "GML"),
                            ("GeoJSON", "GeoJSON"),
                            ("REST", "REST/JSON API"),
                        ],
                        default="ImageWMS",
                        max_length=50,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict, null=True)),
                ("use_proxy", models.BooleanField(default=False)),
                (
                    "connection_timeout",
                    models.IntegerField(blank=True, default=10, null=True),
                ),
                (
                    "read_timeout",
                    models.IntegerField(blank=True, default=30, null=True),
                ),
            ],
            options={
                "verbose_name": "Secure Map Service",
                "verbose_name_plural": "Secure Map Services",
            },
        ),
    ]
