# Generated by Django 5.2.9 on 2026-03-16 18:38

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_services', '0002_secureimageryservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secureimageryservice',
            old_name='metadata',
            new_name='params',
        ),
        migrations.AddField(
            model_name='secureimageryservice',
            name='authentication_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secureimageryservice',
            name='authentication_method',
            field=models.CharField(blank=True, choices=[('api_key', 'API Key'), ('oauth', 'OAuth')], max_length=100),
        ),
        migrations.AlterField(
            model_name='secureimageryservice',
            name='api_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
