# Generated by Django 5.2.9 on 2026-03-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_services', '0003_rename_metadata_secureimageryservice_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureimageryservice',
            name='hide_api_key',
            field=models.BooleanField(default=True),
        ),
    ]
