# Generated by Django 5.2.9 on 2026-08-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_services", "0003_securemapservice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securemapservice",
            name="service_type",
            field=models.CharField(
                choices=[("ImageWMS", "WMS"), ("GML", "GML")],
                default="ImageWMS",
                max_length=50,
            ),
        ),
    ]
