# Generated by Django 5.2.15 on 2026-08-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_services", "0004_alter_securemapservice_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securemapservice",
            name="legend_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="securemapservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("ImageWMS", "WMS"),
                    ("GML", "GML"),
                    ("GeoJSON", "GeoJSON"),
                    ("REST", "REST/JSON API"),
                ],
                default="ImageWMS",
                max_length=50,
            ),
        ),
    ]
