# Generated by Django 5.2.17 on 2026-09-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_services", "0005_alter_securemapservice_legend_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securemapservice",
            name="connection_timeout",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name="securemapservice",
            name="read_timeout",
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
