# Generated by Django 5.2.17 on 2026-08-25 01:48

import django.db.models.deletion
import tethys_services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_services", "0005_alter_securemapservice_legend_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasemapService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("attribution", models.CharField(blank=True, max_length=255)),
                ("min_zoom", models.IntegerField(default=0)),
                ("max_zoom", models.PositiveSmallIntegerField(default=22)),
            ],
        ),
        migrations.CreateModel(
            name="BaseMapImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to=tethys_services.models.original_basemap_upload_path
                    ),
                ),
                (
                    "generated_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=tethys_services.models.generated_basemap_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("failed", "Failed"),
                            ("ready", "Ready"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("srs", models.CharField(blank=True, max_length=64, null=True)),
                ("wkt", models.TextField(blank=True, null=True)),
                ("min_x", models.FloatField(blank=True, null=True)),
                ("min_y", models.FloatField(blank=True, null=True)),
                ("max_x", models.FloatField(blank=True, null=True)),
                ("max_y", models.FloatField(blank=True, null=True)),
                (
                    "basemap_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tethys_services.basemapservice",
                    ),
                ),
            ],
        ),
    ]
