# Generated by Django 5.2.17 on 2026-08-25 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_services', '0006_basemapservice_basemapimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemapimage',
            name='basemap_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tethys_services.basemapservice'),
        ),
    ]
