# Generated by Django 5.2.17 on 2026-09-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tethys_services", "0006_securemapservice_connection_timeout_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="securemapservice",
            old_name="oauth_provider",
            new_name="oauth2_provider",
        ),
        migrations.AlterField(
            model_name="securemapservice",
            name="authentication_method",
            field=models.CharField(
                blank=True,
                choices=[("api_key", "API Key"), ("oauth2", "OAuth2")],
                max_length=100,
            ),
        ),
    ]
