# Generated by Django 5.2.17 on 2026-08-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_services', '0007_alter_basemapimage_basemap_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemapimage',
            name='georeference_bounds',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basemapimage',
            name='georeference_epsg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basemapimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('ready', 'Ready'), ('needs_georeference', 'Needs Georeference')], default='pending', max_length=30),
        ),
    ]
