# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import tethys_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_services', '0008_auto_20151023_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentStoreService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('host', models.CharField(default=b'localhost', max_length=255)),
                ('port', models.IntegerField(default=5435, validators=[tethys_services.models.validate_persistent_store_port])),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('engine', models.CharField(choices=[(b'postgresql', b'PostgreSQL')], default=b'postgresql', max_length=50)),
            ],
            options={
                'verbose_name': 'Persistent Store Service',
                'verbose_name_plural': 'Persistent Store Services',
            },
        ),
    ]
