# Generated by Django 5.2.17 on 2026-10-01

import django.db.models.deletion
import tethys_services.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_services', '0008_basemapimage_georeference_bounds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasemapCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mbtiles_file', models.FileField(upload_to=tethys_services.models.basemap_capture_upload_path)),
                ('tile_format', models.CharField(default='png', max_length=10)),
                ('min_zoom', models.PositiveSmallIntegerField()),
                ('max_zoom', models.PositiveSmallIntegerField()),
                ('min_x', models.FloatField()),
                ('min_y', models.FloatField()),
                ('max_x', models.FloatField()),
                ('max_y', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basemap_captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='basemapimage',
            name='source_file',
            field=models.FileField(blank=True, upload_to=tethys_services.models.original_basemap_upload_path),
        ),
        migrations.AddField(
            model_name='basemapimage',
            name='capture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='tethys_services.basemapcapture'),
        ),
    ]
