# Generated by Django 5.2.7 on 2025-10-31 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tethys_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_package', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_apps', to='tethys_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant App',
                'verbose_name_plural': 'Tenant Apps',
                'unique_together': {('tenant', 'app_package')},
            },
        ),
    ]
