# Generated by Django 2.2.8 on 2020-01-18 02:43

from django.db import migrations, models
import django.db.models.deletion
from tethys_config.init import initial_settings, reverse_init


class Migration(migrations.Migration):

    replaces = [('tethys_config', '0001_initial_20')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
            ],
            options={
                'verbose_name': 'Settings Category',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tethys_config.SettingsCategory')),
            ],
        ),
        migrations.RunPython(initial_settings, reverse_init),
    ]
