# Generated by Django 3.2.12 on 2022-08-12 17:03

from django.db import migrations, models
import django.db.models.deletion
from tethys_config.init import (
    initial_settings,
    reverse_init,
    custom_settings,
    reverse_custom,
)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SettingsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=30)),
            ],
            options={
                "verbose_name": "Settings Category",
                "verbose_name_plural": "Site Settings",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=30)),
                ("content", models.TextField(blank=True, max_length=500)),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tethys_config.settingscategory",
                    ),
                ),
            ],
        ),
        migrations.RunPython(initial_settings, reverse_init),
        migrations.RunPython(custom_settings, reverse_custom),
    ]
