# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import tethys_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_config', '0001_initial_20'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProxyInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('endpoint', models.CharField(max_length=1024, validators=[tethys_services.models.validate_url])),
                ('logo_url', models.CharField(blank=True, max_length=100, validators=[tethys_services.models.validate_url])),
                ('description', models.CharField(blank=True, max_length=2048)),
            ],
            options={
                'verbose_name': 'App Proxy Instance',
                'verbose_name_plural': 'App Proxy Instances',
            },
        ),
    ]
