# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 04:19
from __future__ import unicode_literals
from django.db import migrations
from django.utils import timezone


def settings14to20(apps, schema_editor):
    """
    Update settings to be compatible with 2.0:
    * Remove /static/ from all static files paths.
    """
    # Figure out what time it is right now
    now = timezone.now()

    # Get current settings
    Setting = apps.get_model('tethys_config', 'Setting')
    all_settings = Setting.objects.all()

    for setting in all_settings:
        setting.content = setting.content.replace('/static/', '')
        setting.content = setting.content.replace('static/', '')
        setting.save()


def settings20to14(apps, schema_editor):
    """
    Reverse updates applied while migrating from 2.0 to 1.4.
    """
    # nothing to reverse really...
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_config', '0005_auto_20151023_1720'),
    ]

    operations = [
        migrations.RunPython(settings14to20, settings20to14),
    ]
